// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMPhE3ZoEiiLfW6WJ5fbQXW19uJpOADoE',
    appId: '1:873729559970:web:47f493443bd073bdee76fb',
    messagingSenderId: '873729559970',
    projectId: 'weather-wardrobe-70636',
    authDomain: 'weather-wardrobe-70636.firebaseapp.com',
    storageBucket: 'weather-wardrobe-70636.firebasestorage.app',
    measurementId: 'G-7WRS0B0XJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgZZEsAWc7e9zyZUbdmjq5IeRJqWW-IOY',
    appId: '1:873729559970:android:a3ccc0016a08b2f9ee76fb',
    messagingSenderId: '873729559970',
    projectId: 'weather-wardrobe-70636',
    storageBucket: 'weather-wardrobe-70636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvTFOlEUxWcX1kCctKVelA4ZGES724HJ4',
    appId: '1:873729559970:ios:e166fb68d5d3a77eee76fb',
    messagingSenderId: '873729559970',
    projectId: 'weather-wardrobe-70636',
    storageBucket: 'weather-wardrobe-70636.firebasestorage.app',
    iosBundleId: 'com.example.weatherWardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMPhE3ZoEiiLfW6WJ5fbQXW19uJpOADoE',
    appId: '1:873729559970:web:2cb1d272a4742f53ee76fb',
    messagingSenderId: '873729559970',
    projectId: 'weather-wardrobe-70636',
    authDomain: 'weather-wardrobe-70636.firebaseapp.com',
    storageBucket: 'weather-wardrobe-70636.firebasestorage.app',
    measurementId: 'G-5XK4V52JGE',
  );
}
